name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check-pr:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup_environment

      - name: Install Dependencies
        run: |
          task init

      - name: Lint PR
        run: |
          task lint

      - name: Test PR with Coverage
        run: |
          task test-coverage-run
        env:
          TESTS_ENVIRONMENT: CI

      - name: Report Coverage
        id: report_coverage
        uses: ovsds/run-with-output-action@v1
        with:
          run: task test-coverage-report

      - name: Post Coverage Report as Comment
        uses: ovsds/create-or-update-unique-comment-action@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Coverage report:
            ```
            ${{ steps.report_coverage.outputs.stdout }}
            ```
          unique-body-includes: |
            Coverage report:
